package com.bw.movie.green.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.movie.green.bean.LoginDaoBean;
import com.bw.movie.green.bean.WechatLoginBean;
import com.bw.movie.green.bean.FenLei1;

import com.bw.movie.green.dao.LoginDaoBeanDao;
import com.bw.movie.green.dao.WechatLoginBeanDao;
import com.bw.movie.green.dao.FenLei1Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginDaoBeanDaoConfig;
    private final DaoConfig wechatLoginBeanDaoConfig;
    private final DaoConfig fenLei1DaoConfig;

    private final LoginDaoBeanDao loginDaoBeanDao;
    private final WechatLoginBeanDao wechatLoginBeanDao;
    private final FenLei1Dao fenLei1Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginDaoBeanDaoConfig = daoConfigMap.get(LoginDaoBeanDao.class).clone();
        loginDaoBeanDaoConfig.initIdentityScope(type);

        wechatLoginBeanDaoConfig = daoConfigMap.get(WechatLoginBeanDao.class).clone();
        wechatLoginBeanDaoConfig.initIdentityScope(type);

        fenLei1DaoConfig = daoConfigMap.get(FenLei1Dao.class).clone();
        fenLei1DaoConfig.initIdentityScope(type);

        loginDaoBeanDao = new LoginDaoBeanDao(loginDaoBeanDaoConfig, this);
        wechatLoginBeanDao = new WechatLoginBeanDao(wechatLoginBeanDaoConfig, this);
        fenLei1Dao = new FenLei1Dao(fenLei1DaoConfig, this);

        registerDao(LoginDaoBean.class, loginDaoBeanDao);
        registerDao(WechatLoginBean.class, wechatLoginBeanDao);
        registerDao(FenLei1.class, fenLei1Dao);
    }
    
    public void clear() {
        loginDaoBeanDaoConfig.clearIdentityScope();
        wechatLoginBeanDaoConfig.clearIdentityScope();
        fenLei1DaoConfig.clearIdentityScope();
    }

    public LoginDaoBeanDao getLoginDaoBeanDao() {
        return loginDaoBeanDao;
    }

    public WechatLoginBeanDao getWechatLoginBeanDao() {
        return wechatLoginBeanDao;
    }

    public FenLei1Dao getFenLei1Dao() {
        return fenLei1Dao;
    }

}
